// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8Fip-LGn7K8N9USBZt_kI3db7eOCEiPY',
    appId: '1:478405566447:web:0cb062596cf1c40118201a',
    messagingSenderId: '478405566447',
    projectId: 'delivery-app-v2-36c42',
    authDomain: 'delivery-app-v2-36c42.firebaseapp.com',
    storageBucket: 'delivery-app-v2-36c42.firebasestorage.app',
    measurementId: 'G-67RFLHPSTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqlSvfPnWe7E7CsTaEeosSDX5j_yhPcyQ',
    appId: '1:478405566447:android:7a4b63dd483279a918201a',
    messagingSenderId: '478405566447',
    projectId: 'delivery-app-v2-36c42',
    storageBucket: 'delivery-app-v2-36c42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGsmaXvX1D-qKtqCNJ9Ihp1QTpsFPz1V0',
    appId: '1:478405566447:ios:6b0d82766c55279018201a',
    messagingSenderId: '478405566447',
    projectId: 'delivery-app-v2-36c42',
    storageBucket: 'delivery-app-v2-36c42.firebasestorage.app',
    iosBundleId: 'com.example.appDeliberyRepartidorV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGsmaXvX1D-qKtqCNJ9Ihp1QTpsFPz1V0',
    appId: '1:478405566447:ios:6b0d82766c55279018201a',
    messagingSenderId: '478405566447',
    projectId: 'delivery-app-v2-36c42',
    storageBucket: 'delivery-app-v2-36c42.firebasestorage.app',
    iosBundleId: 'com.example.appDeliberyRepartidorV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8Fip-LGn7K8N9USBZt_kI3db7eOCEiPY',
    appId: '1:478405566447:web:3b21e2be7b1d984c18201a',
    messagingSenderId: '478405566447',
    projectId: 'delivery-app-v2-36c42',
    authDomain: 'delivery-app-v2-36c42.firebaseapp.com',
    storageBucket: 'delivery-app-v2-36c42.firebasestorage.app',
    measurementId: 'G-68LBK2TLK9',
  );
}
